version: "3.2"

services:

  server:
    image: server
    networks:
      - frontend
      - backend
    expose:
      - "3000"
      - "3006"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - frontend

  db:
    image: mariadb
    restart: always
    networks:
      backend:
       ipv4_address: 20.20.4.31   
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: quiz
      MYSQL_USER: quiz
      MYSQL_PASSWORD: xxxx
    expose:
      - '3306'
  gluster: 
    image: gluster
    depends_on:
      - nas1
      - nas2
      - nas3
    networks:
      backend:
       ipv4_address: 20.20.4.20  
    privileged: true
  nas1: 
    image: nas
    networks:
      backend:
       ipv4_address: 20.20.4.21  
    privileged: true 
  nas2: 
    image: nas
    networks:
      backend:
       ipv4_address: 20.20.4.22  
    privileged: true
  nas3: 
    image: nas
    networks:
      backend:
       ipv4_address: 20.20.4.23   
    privileged: true
networks:
  frontend:
    driver: bridge
    ipam:
     config:
       - subnet: 20.20.3.0/24
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 20.20.4.0/24
